### ISSUE TITLE
Add preview generation when uploading an image

### ISSUE THREAD

**Issue by ulin-evgeny** [RonasIT/laravel-media#11]

**Comment by ulin-evgeny** [comment]
Done.

**Comment by DenTray** [comment]
@ulin-evgeny as discussed, please test it with the GCS storage driver

**Comment by RGO230** [comment]
@DenTray done please check

**Comment by DenTray** [comment]
@RGO230 not works for me with `gcs`  driver

<img width="1382" alt="image" src="https://github.com/user-attachments/assets/ec81d460-ba6c-4e75-978e-52b4e18005b8">

**Comment by DenTray** [comment]
Released in 0.0.5-beta
