### ISSUE TITLE
Generate OpenAPI documentation

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-media#6]

**Comment by DenTray** [comment]
@ulin-evgeny please update the following:
1. Description should be "Documentation for the Media API, describes all endpoints, provided by the package."
2. Remove `contact` and `termsOfService` keys
3. `version` should be `0.0.1`

**Comment by ulin-evgeny** [comment]
Done.

**Comment by DenTray** [comment]
@ulin-evgeny I've tries to install the `^0.0.2@beta` version, added config by the Readme description and doc are not displaying, could you please check it?

**Comment by ulin-evgeny** [comment]
Done.

**Comment by DenTray** [comment]
@ulin-evgeny great! thanks!
